package Server;


public class Font {
	int width = 15;
	int height = 20;
	String folder = "Font/";

	FontImg a = new FontImg(width,height,folder + "a.png");
	FontImg b = new FontImg(width,height,folder + "b.png");
	FontImg c = new FontImg(width,height,folder + "c.png");
	FontImg d = new FontImg(width,height,folder + "d.png");
	FontImg e = new FontImg(width,height,folder + "e.png");
	FontImg f = new FontImg(width,height,folder + "f.png");
	FontImg g = new FontImg(width,height,folder + "g.png");
	FontImg h = new FontImg(width,height,folder + "h.png");
	FontImg i = new FontImg(width,height,folder + "i.png");
	FontImg j = new FontImg(width,height,folder + "j.png");
	FontImg k = new FontImg(width,height,folder + "k.png");
	FontImg l = new FontImg(width,height,folder + "l.png");
	FontImg m = new FontImg(width,height,folder + "m.png");
	FontImg n = new FontImg(width,height,folder + "n.png");
	FontImg o = new FontImg(width,height,folder + "o.png");
	FontImg p = new FontImg(width,height,folder + "p.png");
	FontImg q = new FontImg(width,height,folder + "q.png");
	FontImg r = new FontImg(width,height,folder + "r.png");
	FontImg s = new FontImg(width,height,folder + "s.png");
	FontImg t = new FontImg(width,height,folder + "t.png");
	FontImg u = new FontImg(width,height,folder + "u.png");
	FontImg v = new FontImg(width,height,folder + "v.png");
	FontImg w = new FontImg(width,height,folder + "w.png");
	FontImg x = new FontImg(width,height,folder + "x.png");
	FontImg y = new FontImg(width,height,folder + "y.png");
	FontImg z = new FontImg(width,height,folder + "z.png");
	FontImg zero = new FontImg(width,height,folder + "0.png");
	FontImg one = new FontImg(width,height,folder + "1.png");
	FontImg two = new FontImg(width,height,folder + "2.png");
	FontImg three = new FontImg(width,height,folder + "3.png");
	FontImg four = new FontImg(width,height,folder + "4.png");
	FontImg five = new FontImg(width,height,folder + "5.png");
	FontImg six = new FontImg(width,height,folder + "6.png");
	FontImg seven = new FontImg(width,height,folder + "7.png");
	FontImg eight = new FontImg(width,height,folder + "8.png");
	FontImg nine = new FontImg(width,height,folder + "9.png");
	FontImg tilde = new FontImg(width,height,folder + "tilde.png");
	FontImg exclamationPoint = new FontImg(width,height,folder + "!.png");
	FontImg at = new FontImg(width,height,folder + "@.png");
	FontImg hashtag = new FontImg(width,height,folder + "#.png");
	FontImg dollarSign = new FontImg(width,height,folder + "$.png");
	FontImg percent = new FontImg(width,height,folder + "%.png");
	FontImg carot = new FontImg(width,height,folder + "^.png");
	FontImg ampersand = new FontImg(width,height,folder + "&.png");
	FontImg asterisk = new FontImg(width,height,folder + "asterisk.png");
	FontImg openingParen = new FontImg(width,height,folder + "(.png");
	FontImg closingParen = new FontImg(width,height,folder + ").png");
	FontImg minus = new FontImg(width,height,folder + "-.png");
	FontImg underScore = new FontImg(width,height,folder + "_.png");
	FontImg plus = new FontImg(width,height,folder + "+.png");
	FontImg equal = new FontImg(width,height,folder + "=.png");
	FontImg openingCurly = new FontImg(width,height,folder + "{.png");
	FontImg closingCurly = new FontImg(width,height,folder + "}.png");
	FontImg openingBracket = new FontImg(width,height,folder + "[.png");
	FontImg closingBracket = new FontImg(width,height,folder + "].png");
	FontImg verticalBar = new FontImg(width,height,folder + "verticalBar.png");
	FontImg backSlash = new FontImg(width,height,folder + "backwardSlash.png");
	FontImg colon = new FontImg(width,height,folder + "colon.png");
	FontImg semiColon = new FontImg(width,height,folder + ";.png");
	FontImg apostrophe = new FontImg(width,height,folder + "'.png");
	FontImg quotationMark = new FontImg(width,height,folder + "quotationMark.png");
	FontImg openingChevron = new FontImg(width,height,folder + "lessThan.png");
	FontImg closingChevron = new FontImg(width,height,folder + "greaterThan.png");
	FontImg comma = new FontImg(width,height,folder + ",.png");
	FontImg period = new FontImg(width,height,folder + "..png");
	FontImg forwardSlash = new FontImg(width,height,folder + "forwardSlash.png");
	FontImg questionMark = new FontImg(width,height,folder + "questionMark.png");
	FontImg lolwat = new FontImg(width,height,folder + "unknown.png");
	int charNum = 68;
}
